### ISSUE TITLE
API for storing secrets

### ISSUE THREAD

**Issue by h1alexbel** [tracehubpm/pmo#44]
As I described [here](https://github.com/tracehubpm/tracehub?tab=readme-ov-file#secret-variables), we need to store secrets inside our database, to give a possibility to a user to reference the values from it:
```yaml
# we are in project.yml
...
backlog:
 type: JIRA
 jira-url: ${jira-url}
...
```
we should create and maintain API in PMO for storing secrets, data schema probably should be something like this:

* `key`: the key of the secret
* `value`: the value of the secret

API should be simply stupid:
* save the secret with `key`, `value`
* get the `value` by the `key`
